# Generated by Django 5.0.6 on 2024-08-26 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adress",
            new_name="Address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="adress",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="adress",
            new_name="address",
        ),
    ]
